### ISSUE TITLE
Segfault when backspacing on an empty buffer

### ISSUE THREAD

**Issue by elfifae** [malleusinferni/wry#1]
Pretty simple thing to report: Trying to backspace when the linebuffer is empty results in a segmentation fault.

Running Arch Linux on an i386 proc (Intel Pentium M "Banias" 1.5), gcc 4.7.1

gdb backtrace:

Program received signal SIGSEGV, Segmentation fault.
0xb7e595b0 in __strncpy_sse2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0xb7e595b0 in __strncpy_sse2 () from /usr/lib/libc.so.6
#1  0x08049110 in del_buf (i=0) at wry.c:197
#2  0x00000000 in ?? ()

EDIT: whoops, I was still thinking in ascending-order backtraces thanks to Python. Assumptions trimmed out.

**Comment by snacsnoc** [comment]
I'm unable to reproduce this under Debian, with gcc 4.8.2. Are you attempting to backspace on an empty line?

**Comment by elfifae** [comment]
Actually I believe he fixed it ages ago but never closed my issue, haha. Whoops!
